version: "3.8"
services:
  cardano-node:
    image: ghcr.io/intersectmbo/cardano-node:11.0.1
    container_name: cardano-node
    environment:
      - NETWORK=mainnet
    volumes:
      - ./cardano/db:/data/db
      - ./cardano/ipc:/ipc
    ports:
      - "3001:3001"
